### ISSUE TITLE
Requesting to join to develop my skills

### ISSUE THREAD

**Issue by saravanakumarbalasubramanian** [DuolearnHQ/wealthwise#12]
Hi there, I am saravana, I would like to implement my skills under various conditions so, I would like to work together and develop a projects.

**Comment by pavankpdev** [comment]
Hey @saravanakumarbalasubramanian, You should pick an existing [issue](https://github.com/DuolearnHQ/wealthwise/issues) and drop a comment over there. 

Closing this issue for now. Reach out to me if you still need any assistance.
